language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
    - rustup component add rustfmt
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake libgtk-3-dev

script:
    - cd iui
    - cargo build --verbose --tests --examples
    - xvfb-run cargo test
