language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

dist: bionic
addons:
  apt:
    packages:
      - libgtk-3-dev
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build
      - xvfb

install:
  - pip3 install meson
  - rustup component add rustfmt

env:
  - RUST_BACKTRACE=1

script:
  - cargo build --verbose --tests --examples
  - xvfb-run cargo test --verbose
  - xvfb-run cargo test --verbose --features static
